#!/bin/bash

# lk_mysql_get_cnf [USER [PASSWORD [HOST]]]
function lk_mysql_get_cnf() {
    cat <<EOF
# Generated by ${FUNCNAME[1]:-${FUNCNAME[0]}}
[client]
user="$(lk_escape "${1-$DB_USER}" "\\" '"')"
password="$(lk_escape "${2-$DB_PASSWORD}" "\\" '"')"
host="$(
        lk_escape "${3-${DB_HOST-${LK_MYSQL_HOST:-localhost}}}" "\\" '"'
    )"${LK_MY_CNF_OPTIONS:+
$LK_MY_CNF_OPTIONS}
EOF
}

function lk_mysql_write_cnf() {
    LK_MY_CNF=${LK_MY_CNF:-$HOME/.lk_mysql.cnf}
    lk_mysql_get_cnf "$@" >"$LK_MY_CNF"
}

function lk_mysql() {
    [ -n "${LK_MY_CNF:-}" ] || lk_warn "LK_MY_CNF not set" || return
    [ -f "$LK_MY_CNF" ] || lk_warn "file not found: $LK_MY_CNF" || return
    mysql --defaults-file="$LK_MY_CNF" "$@"
}

function lk_mysql_connects() {
    lk_mysql --execute="\\q" ${1+"$1"}
}
