#!/usr/bin/env bash

. lk-bash-load.sh || exit
lk_require git

s=/

HOOK=$0
[ "${HOOK#/}" != "$HOOK" ] || HOOK=$PWD/$HOOK
LOG_FILE=/tmp/${HOOK//"$s"/__}.log
printf '\n====> %s invoked\nArguments:\n%s\nEnvironment:\n%s\n' "$HOOK" \
    "$(lk_args "$@" | sed 's/^/  /')" \
    "$(printenv | sed 's/^/  /')" |
    lk_log >>"$LOG_FILE"
exec > >(tee >(lk_log >>"$LOG_FILE")) 2>&1

cd "${PWD%/.git}"
lk_mktemp_with INVALID gnu_xargs -0r shfmt -l -i 2 \
    < <(shfmt -l -i 4 . | tr '\n' '\0')

[ ! -s "$INVALID" ] || {
    lk_tty_error -r "Invalid formatting:" $'\n'"$(lk_pass cat "$INVALID")" ||
        lk_die ""
}

./src/build-all.sh --no-write ||
    lk_die "Rebuild required before committing changes"
