#!/bin/sh
xset -b
xset s 240 60
export XSECURELOCK_DIM_TIME_MS=750
export XSECURELOCK_WAIT_TIME_MS=60000

XSECURELOCK_FONT="$(xfconf-query -c xsettings -p /Gtk/MonospaceFontName)" &&
    export XSECURELOCK_FONT ||
    unset XSECURELOCK_FONT

export XSECURELOCK_SAVER="saver_blank"
export XSECURELOCK_SHOW_DATETIME=1
export XSECURELOCK_AUTH_TIMEOUT=20
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

xfconf-query -c xfce4-session -p /general/LockCommand -n -t string -s "xset s activate"

. /etc/xdg/xfce4/xinitrc
