#!/usr/bin/env bash

# Generated by ({:printf '%s at %s' "$(lk_realpath "$0")" "$(lk_date_log)":})

set -euo pipefail
export LK_BASE={{"LK_BASE"}}
. "$LK_BASE/lib/bash/common.sh"

unset LK_NO_LOG

lk_log_open "/var/log/${LK_PATH_PREFIX}policy-rc.log"
lk_log_tty_all_off

lk_tty_print "Checking environment"

PROVISIONING=N
UPGRADING=N
# 104 = Action allowed
STATUS=104

LOCK_FILE=/tmp/lk-provision-hosting.sh.lock
exec 9>"$LOCK_FILE"

# If provisioning is in progress and packages are being installed rather than
# upgraded, disallow postinst actions to prevent services starting before
# they've been configured
if ! flock -n 9; then
    PROVISIONING=Y
    if [[ -z ${_LK_APT_UPGRADE-} ]]; then
        [[ ${DPKG_MAINTSCRIPT_NAME-} != postinst ]] ||
            # 101 = Action not allowed
            STATUS=101
    else
        UPGRADING=Y
    fi
else
    exec 9>&- &&
        rm -f -- "$LOCK_FILE" || true
fi

printf '%s\t%s\n' \
    "dpkg script" "${DPKG_MAINTSCRIPT_NAME:-<unknown>}" \
    "Provisioning" "$PROVISIONING" \
    "Upgrading" "$UPGRADING" \
    "Exit status" "$STATUS" | IFS=$'\t' lk_tty_pairs_detail

(exit "$STATUS") || lk_die ""
