#!/bin/sh
# shellcheck disable=SC1090,SC2015,SC2030,SC2031

[ ! -f "/etc/default/lk-platform" ] || . "/etc/default/lk-platform"
LK_PATH_PREFIX="${LK_PATH_PREFIX:-lk-}"
LK_PATH_PREFIX_ALPHA="${LK_PATH_PREFIX_ALPHA:-$(echo "$LK_PATH_PREFIX" |
    sed 's/[^a-zA-Z0-9]//g')}"
[ ! -f "${HOME:+$HOME/.${LK_PATH_PREFIX}settings}" ] ||
    . "$HOME/.${LK_PATH_PREFIX}settings"
lk_esc() { echo "$1" | sed -Ee 's/\\/\\\\/g' -e 's/[$`"]/\\&/g'; }

[ -n "${LK_BASE:-}" ] ||
    eval "$(
        if [ ! -L "$0" ] &&
            LK_BASE="$(cd "${0%/*}/../.." && pwd -P)" &&
            [ -d "$LK_BASE/lib/bash" ]; then
            echo "LK_BASE=\"$(lk_esc "$LK_BASE")\""
        else
            echo "$0: LK_BASE not set" >&2
        fi
    )"
export LK_BASE

eval "$(. "$LK_BASE/lib/bash/env.sh")"

! type autorandr >/dev/null 2>&1 ||
    autorandr -c --default default --force ||
    AUTORANDR_PROFILE_FOLDER="$HOME/.config/autorandr/default" \
        "$LK_BASE/lib/autorandr/postswitch" || true

export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
QT_FONT_DPI="$(xdpyinfo |
    grep -Eo '^[[:space:]]+resolution:[[:space:]]*[0-9]+x[0-9]+' |
    grep -Eo '[0-9]+' | head -n1)" &&
    export QT_FONT_DPI ||
    unset QT_FONT_DPI

xset -b
xset s "${LK_DIM_AFTER:=240}" "${LK_DIM_TIME:=60}"
XSECURELOCK_DIM_TIME_MS="${XSECURELOCK_DIM_TIME_MS:-750}"
XSECURELOCK_WAIT_TIME_MS="${XSECURELOCK_WAIT_TIME_MS:-$((LK_DIM_TIME * 1000))}"
unset LK_DIM_AFTER LK_DIM_TIME

if XSECURELOCK_FONT="${XSECURELOCK_FONT:-$(
    xfconf-query -c xsettings -p /Gtk/MonospaceFontName
)}"; then
    export XSECURELOCK_FONT
else
    unset XSECURELOCK_FONT
fi

XSECURELOCK_SAVER="${XSECURELOCK_SAVER:-saver_blank}"
XSECURELOCK_PASSWORD_PROMPT="${XSECURELOCK_PASSWORD_PROMPT:-time}"
XSECURELOCK_AUTH_TIMEOUT="${XSECURELOCK_AUTH_TIMEOUT:-20}"
XSECURELOCK_SHOW_DATETIME="${XSECURELOCK_SHOW_DATETIME:-1}"

export XSECURELOCK_DIM_TIME_MS XSECURELOCK_WAIT_TIME_MS \
    XSECURELOCK_SAVER XSECURELOCK_PASSWORD_PROMPT XSECURELOCK_AUTH_TIMEOUT \
    XSECURELOCK_SHOW_DATETIME

xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

xfconf-query -c xfce4-session \
    -p /general/LockCommand -n -t string -s "xset s activate"

. /etc/xdg/xfce4/xinitrc
