apache_modules:
  - mod_rewrite

# Known to throw CLI exceptions
skip-plugins:
  - addthis
  - all-in-one-redirection
  - event-calendar-exporter
  - facebook
  - find-replace
  - force-https-littlebizzy
  - force-ssl
  - hide_my_wp
  - simplemap
  - the-events-calendar
