#!/bin/bash

set -euo pipefail

. "$LK_BASE/lib/bash/common.sh"

if [[ -f $AUTORANDR_PROFILE_FOLDER/dpi ]] &&
    DPI=$(<"$AUTORANDR_PROFILE_FOLDER/dpi") &&
    [[ $DPI =~ ^[0-9]+$ ]]; then

    STATE_FILE=/tmp/autorandr_profile_${EUID}_${DISPLAY%.*}
    LAST_PROFILE=
    [[ ! -f $STATE_FILE ]] ||
        LAST_PROFILE=$(<"$STATE_FILE")

    lk_require linux
    CURRENT_DPI=$(lk_x_dpi) || CURRENT_DPI=-1

    xrandr --dpi "$DPI"

    case "${XDG_CURRENT_DESKTOP-}" in
    XFCE)
        "$LK_BASE/bin/lk-xfce4-apply-dpi.sh" "$DPI"
        if ((CURRENT_DPI != DPI)) || [[ $LAST_PROFILE != "$AUTORANDR_CURRENT_PROFILE" ]]; then
            sleep 1
            ! RUNNING=$(pgrep -xu "$USER" xfce4-panel | tail -n1 |
                lk_ps_running_seconds) ||
                ((RUNNING < 10)) || lk_tty_run xfce4-panel -r || true
        fi
        ;;&
    *)
        echo "Xft.dpi: $DPI" | xrdb -merge
        ;;
    esac

    printf '%s\n' "$AUTORANDR_CURRENT_PROFILE" >"$STATE_FILE"
fi

for XKB_FILE in \
    "$AUTORANDR_PROFILE_FOLDER/xkb" \
    ~/.config/autorandr/xkb \
    /etc/xdg/autorandr/xkb; do
    [ ! -f "$XKB_FILE" ] || break
    XKB_FILE=
done
[ -z "$XKB_FILE" ] ||
    "$LK_BASE/bin/lk-xkb-load.sh" "$XKB_FILE"

! type -P displaycal-apply-profiles >/dev/null ||
    displaycal-apply-profiles

! killall devilspie2 -u "$USER" 2>/dev/null || {
    nohup devilspie2 &>/dev/null &
    disown
}
