#!/bin/bash

set -euo pipefail

if [ -f "$AUTORANDR_PROFILE_FOLDER/dpi" ] &&
    DPI="$(cat "$AUTORANDR_PROFILE_FOLDER/dpi")" &&
    [[ $DPI =~ ^[0-9]+$ ]]; then

    xrandr --dpi "$DPI"

    case "${XDG_CURRENT_DESKTOP-}" in
    XFCE)
        "$LK_BASE/bin/lk-xfce4-apply-dpi.sh" "$DPI"
        ;;&
    *)
        echo "Xft.dpi: $DPI" | xrdb -merge
        ;;
    esac
fi

for XKB_FILE in \
    "$AUTORANDR_PROFILE_FOLDER/xkb" \
    ~/.config/autorandr/xkb \
    /etc/xdg/autorandr/xkb; do
    [ ! -f "$XKB_FILE" ] || break
    XKB_FILE=
done
[ -z "$XKB_FILE" ] ||
    "$LK_BASE/bin/lk-xkb-load.sh" "$XKB_FILE"

! type -P displaycal-apply-profiles >/dev/null ||
    displaycal-apply-profiles

! killall devilspie2 -u "$USER" 2>/dev/null || {
    nohup devilspie2 &>/dev/null &
    disown
}
